FROM debian:testing-slim

LABEL maintainer="Ricardo Bánffy <rbanffy@gmail.com>"

ARG USERNAME=hercules
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN DEBIAN_FRONTEND=noninteractive \
    groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    apt update && \
    # apt upgrade -y && \
    apt -y install --no-install-recommends \
    apt-utils \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    cmake \
    flex \
    gawk \
    git \
    libbz2-dev \
    libcap2-bin \
    libltdl-dev \
    libregina3-dev \
    libtool-bin \
    m4 \
    sysvbanner \
    time \
    unzip \
    wget \
    zlib1g-dev

RUN cd /home/${USERNAME}/ && \

    # Get the main repo
    git clone https://github.com/SDL-Hercules-390/hyperion.git && \

    # Remove Hyperion's distribution bundled amd64 binaries
    rm -v /home/${USERNAME}/hyperion/crypto/lib/* && \
    rm -v /home/${USERNAME}/hyperion/decNumber/lib/* && \
    rm -v /home/${USERNAME}/hyperion/SoftFloat/lib/* && \
    rm -v /home/${USERNAME}/hyperion/telnet/lib/* && \

    # Get the external modules
    git clone https://github.com/SDL-Hercules-390/crypto.git && \
    git clone https://github.com/SDL-Hercules-390/decNumber.git && \
    git clone https://github.com/SDL-Hercules-390/SoftFloat.git && \
    git clone https://github.com/SDL-Hercules-390/telnet.git

    # Detect architecture and word size
RUN export ARCH=$( arch ) && \
    echo "Architecture is $ARCH" && \
    if [ "$ARCH" == "x86_64" ]; then \
        echo "Running on x86_64" && \
        export ARCH="amd64"; \
        export WORD_LENGTH=64; \
    elif [ "$ARCH" == "aarch64" ]; then \
        echo "Running on arm64" && \
        export ARCH="aarch64"; \
        export WORD_LENGTH=64; \
    elif [ "$ARCH" == "ppc64le" ]; then \
        echo "Running on ppc64le" && \
        export ARCH="ppc"; \
        export WORD_LENGTH=64; \
    else \
        echo "Couldn't translate architecture $ARCH"; \
        exit 1; \
    fi && \
    echo "Adjusted ARCH is now $ARCH" && \

    # Build the external crypto module
    mkdir /home/$USERNAME/crypto32.Release && \
    cd /home/$USERNAME/crypto32.Release && \
    cmake ../crypto && \
    make && \

    mkdir /home/$USERNAME/crypto64.Release && \
    cd /home/$USERNAME/crypto64.Release && \
    cmake ../crypto && \
    make && \

    mkdir /home/$USERNAME/hyperion/crypto/lib/${ARCH} && \
    cp -v libcrypto*.a /home/$USERNAME/hyperion/crypto/lib/${ARCH}/ && \

    # Build the external decNumber module
    if [ "$WORD_LENGTH"="32" ]; then \
        mkdir /home/$USERNAME/decNumber32.Release && \
        cd /home/$USERNAME/decNumber32.Release && \
        cmake ../decNumber && \
        make; \
    else \
        mkdir /home/$USERNAME/decNumber64.Release && \
        cd /home/$USERNAME/decNumber64.Release && \
        cmake ../decNumber && \
        make; \
    fi && \

    mkdir /home/$USERNAME/hyperion/decNumber/lib/${ARCH} && \
    cp -v libdecNumber*.a /home/$USERNAME/hyperion/decNumber/lib/${ARCH}/ && \

    # Build the external SoftFloat module
    mkdir /home/$USERNAME/SoftFloat32.Release && \
    cd /home/$USERNAME/SoftFloat32.Release && \
    cmake ../SoftFloat && \
    make && \

    mkdir /home/$USERNAME/SoftFloat64.Release && \
    cd /home/$USERNAME/SoftFloat64.Release && \
    cmake ../SoftFloat && \
    make && \

    mkdir /home/$USERNAME/hyperion/SoftFloat/lib/${ARCH} && \
    cp -v libSoftFloat*.a /home/$USERNAME/hyperion/SoftFloat/lib/${ARCH}/ && \

    # Build the external telnet module build
    mkdir /home/$USERNAME/telnet32.Release && \
    cd /home/$USERNAME/telnet32.Release && \
    cmake ../telnet && \
    make && \

    mkdir /home/$USERNAME/telnet64.Release && \
    cd /home/$USERNAME/telnet64.Release && \
    cmake ../telnet && \
    make && \

    mkdir /home/$USERNAME/hyperion/telnet/lib/${ARCH} && \
    cp -v libtelnet*.a /home/$USERNAME/hyperion/telnet/lib/${ARCH}/

# Build Hercules
RUN cd /home/$USERNAME/hyperion && \
    ./configure && \
    make install && \
    # Remove unwanted files.
    apt purge -y \
    apt-utils \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    cmake \
    flex \
    gawk \
    git \
    libbz2-dev \
    libcap2-bin \
    libltdl-dev \
    libregina3-dev \
    libtool-bin \
    m4 \
    sysvbanner \
    time \
    unzip \
    wget \
    zlib1g-dev && \
    apt -y autoremove && \
    rm -rf /var/lib/apt/lists/* *.zip && \
    chown -R $USERNAME:$USERNAME /home/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

EXPOSE 3270/TCP
EXPOSE 8038/TCP

CMD ["hercules"]
