# syntax=docker/dockerfile:1

FROM debian:testing-slim

LABEL maintainer="Ricardo Bánffy <rbanffy@gmail.com>"

ARG USERNAME=hercules
ARG USER_UID=1000
ARG USER_GID=$USER_UID

COPY build/mvs-tk5 /tmp/mvs-tk5

RUN DEBIAN_FRONTEND=noninteractive \
        groupadd --gid $USER_GID $USERNAME && \
        useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y --no-install-recommends hercules wget unzip && \
        cd /home/$USERNAME && \
        # Copy the emulator configuration and disk/tape images.
        mv /tmp/mvs-tk5 . && \
        cd mvs-tk5 && \
        chmod +x mvs mvs_ipl mvs_osx start_herc && \
        # Remove unwanted files.
        apt-get purge -y wget unzip && \
        apt-get -y autoremove && \
        rm -rf /var/lib/apt/lists/* /*.zip && \
        chown -R $USERNAME:$USERNAME /home/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME/mvs-tk5

EXPOSE 3270/TCP
EXPOSE 8038/TCP

CMD ["./mvs"]
