# syntax=docker/dockerfile:1

ARG BASE_IMAGE=debian:stable-slim
FROM ${BASE_IMAGE}

LABEL maintainer="Ricardo Bánffy <rbanffy@gmail.com>"

ARG USERNAME=hercules
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN DEBIAN_FRONTEND=noninteractive \
        echo Adding group $USER_GID with name $USERNAME && \
        groupadd --gid $USER_GID $USERNAME && \
        echo Adding user $USERNAME \($USER_UID\) with group $USER_GID && \
        useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y --no-install-recommends hercules ca-certificates && \
        apt-get purge -y ca-certificates && \
        apt-get -y autoremove && \
        rm -rf /var/lib/apt/lists/*

COPY VM370CE.V1.R1.2 /home/$USERNAME/
COPY vm370sixpack-1_3 /home/$USERNAME/e

WORKDIR /home/$USERNAME

RUN chown -R $USERNAME:$USERNAME /home/$USERNAME && \
        # Enable DOS/VS devices.
        sed -i 's/#0361/0361/' vm370ce.conf && \
        sed -i 's/#0362/0362/' vm370ce.conf && \
        sed -i 's/#0363/0363/' vm370ce.conf && \
        sed -i 's/#0364/0364/' vm370ce.conf && \
        # Enable web UI with the MAINT credentials
        sed -i 's/#HTTPPORT       8081/HTTPPORT    8081    AUTH MAINT CPCMS/' vm370ce.conf && \
        # Log off the OPERATOR user from the Hercules console
        echo '/LOGOFF' >> hercules.rc && \
        # Create startup script to handle PRINTER replacement
        echo '#!/bin/sh' > start.sh && \
        echo "if [ -n \"\$PRINTER\" ]; then" >> start.sh && \
        echo "    sed -i \"s|io/print1.listing|\$PRINTER|g\" sixpack.conf" >> start.sh && \
        echo 'fi' >> start.sh && \
        echo 'exec hercules -f sixpack.conf' >> start.sh && \
        chmod +x start.sh && \
        # Remove unwanted files
        rm -f ./*.pdf vm370ce.cmd vm370ce.sh

USER $USERNAME
WORKDIR /home/$USERNAME

EXPOSE 3270/tcp
EXPOSE 8081/tcp

CMD ["./start.sh"]
