# syntax=docker/dockerfile:1

FROM debian:stable-slim

LABEL maintainer="Ricardo Bánffy <rbanffy@gmail.com>"

ARG USERNAME=hercules
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN DEBIAN_FRONTEND=noninteractive \
        # groupadd --gid $USER_GID $USERNAME && \
        # useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
        # apt update && \
        # apt upgrade -y && \
        # apt install -y --no-install-recommends hercules wget unzip ca-certificates && \
        cd /home/$USERNAME && \
        # Dowload the emulator configuration and disk/tape images.
        wget -q https://mvstk4.s3.amazonaws.com/tk4-_v1.00_current.zip && \
        wget -q https://mvstk4.s3.amazonaws.com/tk4-cbt.zip && \
        wget -q https://mvstk4.s3.amazonaws.com/tk4-source.zip && \
        unzip tk4-_v1.00_current.zip && \
        unzip -o tk4-cbt.zip && \
        unzip -o tk4-source.zip && \
        # Remove unwanted files.
        apt purge -y wget unzip ca-certificates && \
        apt -y autoremove && \
        rm -rf /var/lib/apt/lists/* *.zip && \
        chown -R $USERNAME:$USERNAME /home/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

EXPOSE 3270/TCP
EXPOSE 8038/TCP

CMD ["./mvs"]
