# syntax=docker/dockerfile:1

ARG BASE_IMAGE=debian:stable-slim
FROM ${BASE_IMAGE}

LABEL maintainer="Ricardo Bánffy <rbanffy@gmail.com>"

ARG USERNAME=hercules
ARG USER_UID=1000
ARG USER_GID=$USER_UID

WORKDIR /home/$USERNAME

RUN DEBIAN_FRONTEND=noninteractive \
        groupadd --gid $USER_GID $USERNAME && \
        useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y --no-install-recommends hercules wget unzip ca-certificates && \
        # Dowload the emulator configuration and disk/tape images.
        wget -q https://mvstk4.s3.amazonaws.com/tk4-_v1.00_current.zip && \
        wget -q https://mvstk4.s3.amazonaws.com/tk4-cbt.zip && \
        wget -q https://mvstk4.s3.amazonaws.com/tk4-source.zip && \
        unzip tk4-_v1.00_current.zip && \
        unzip -o tk4-cbt.zip && \
        unzip -o tk4-source.zip && \
        # Remove unwanted files.
        apt-get purge -y wget unzip ca-certificates && \
        apt-get -y autoremove && \
        rm -rf /var/lib/apt/lists/* ./*.zip && \
        chown -R $USERNAME:$USERNAME /home/$USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

EXPOSE 3270/tcp
EXPOSE 8038/tcp

CMD ["./mvs"]
